### ISSUE TITLE
methods vs functions

### ISSUE THREAD

**Issue by jmpann** [learn-co-curriculum/js-object-methods-readme#14]
all functions are a property of the Window object. makes all functions not defined on other objects methods of Window

**Comment by gj** [comment]
Hi @jmpann !

Not quite — all _global_ functions are properties of the `window` object (and therefore methods of the `window` object) _in the browser_. Those two distinctions are key. In addition, you can have functions defined inside other functions, IIFEs, and function expressions defined in the global scope with `let` and `const`, to name a few, none of which are defined on the `window` object (or necessarily any object, for that matter).
